services:

  minecraft:
    build:
      context: ./
      dockerfile: docker/minecraft/Dockerfile
    container_name: swordandforge
    image: swordandforge
    ports:
      - 25566:25565
      - 24454:24454/udp
    environment:
      EULA: True
      INIT_MEMORY: 16G
      MAX_MEMORY: 24G
      TYPE: FORGE
      VERSION: "1.20.1"
      FORGE_VERSION: "47.4.0"

    # RAM-DISK
    # volumes:
    # - ./ram_disk:/data

    # DATA FS:
    volumes:
    - ./data:/data
    restart: unless-stopped

networks:
  default:
    name: swordandforge_network
